language: go

go:
  - "1.16.x"
  - "1.15.x"

git:
  depth: 1

install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get -u golang.org/x/lint/golint
  - go install golang.org/x/tools/cmd/cover
  - go install golang.org/x/lint/golint
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - golint .
  - go test -cover -race -count=1 -timeout=30s -run .
  - go test -covermode=count -coverprofile=coverage.out -timeout=90s -run .
  - '[ ! -z "$COVERALLS_TOKEN" ] && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN'
  - go test -benchmem -run=^$  -bench=. -benchmem
